Avoid basic adapter deletion
ernestio/logger pull request #18
Opened 2017-03-02 19:28 UTC by kaitokojiro

Basic logger should be always up, so basically this pull request disables the public interface to disable it.

Additionally a small cleanup has been done, basically by moving all adapters to its own package.

2017-03-02 21:03 UTC, kaitokojiro commented
I've introduced some changes on the file circle.yml as part of [last comit](https://github.com/ernestio/logger/pull/18/commits/57f3cfb3a9bcb63d9b76c73498f3257c1641b22c). 
Those changes allow circleci to successfully manage go relative imports even if the tests are running on top of a fork like this.

2017-03-03 07:31 UTC, adriacidre commented
Cheers! I've created the issue https://github.com/ernestio/ernest/issues/292 to keep track of this feature.

2017-03-06 08:56 UTC, adriacidre requested changes
Looks good to me, however i would like to see some tests forcing the restriction on basic adapter deletion. 
@kaitokojiro do you think you can provide them as part of this pull request?

Cheers!

2017-03-06 08:56 UTC, adriacidre commented on main.go
> +			log.Println("Basic adapter is not optional")
Would be nice to see some tests forcing this restriction

2017-03-07 22:07 UTC, kaitokojiro commented
Hey, that's fine! I'm just working on some related feature, I'll deliver everything together when I'm done.

2017-03-08 12:14 UTC, adriacidre approved these changes

2017-03-08 12:14 UTC, merged

2017-03-08 12:14 UTC, adriacidre commented
Thanks!